uthaira/bedee-app-ui

- src/components/input/SelectGroupInput.stories.tsx
- src/components/input/SelectGroupInput.tsx
- src/components/input/index.ts
> feature: selection group input

- src/components/input/SelectGroupInput.tsx
- src/components/input/TextInput.stories.tsx
- src/components/input/TextInput.tsx
TextInput and storybook
- with helper
- with error
- disabled
-
> feature: TextInput component

- src/components/header/PageHeader.stories.tsx
- src/components/header/PageHeader.tsx
- src/components/header/index.ts
- src/icons/ArrowLeftIcon.tsx
> feat: page header component

- src/components/upload/DocumentUploader.stories.tsx
- src/components/upload/DocumentUploader.tsx
- src/hooks/useFileUploader.ts
- src/icons/UploadIcon.tsx
> Feature Document uploader

- src/components/input/SelectGroupInput.stories.tsx
- src/components/input/SelectGroupInput.tsx
> fix: select group support error

- src/components/badge/Badge.stories.tsx
- src/components/badge/Badge.tsx
> update: Badge sx prop

- src/components/input/DOBPickerInput.tsx
https://github.com/user-attachments/assets/9bc9e195-0ef9-48bc-abdf-efa79e739fea
> fix: dob picker with clear icon

- src/components/input/DOBPickerInput.tsx
> fix: DOB dialog stick with input

- src/components/bottomsheet/BaseBottomSheet.tsx
> fix: close icon absolute position on bottom sheet

- src/components/input/DOBPickerInput.stories.tsx
- src/components/input/DOBPickerInput.tsx
got null after click clear button then will trigger on change
> fix: DOB on clear should call on change

- src/components/input/DOBPickerInput.stories.tsx
- src/components/input/DOBPickerInput.tsx
> update: dob support place holder

- src/toast/toast.tsx
> fix: toast width to 100%

- src/consent/withConsent.tsx
using example
```
export default Consent.withConsent(Authentication.withAuth(ShareSymptomPage), {
onFetchConsent: getConsentDataController,
consentUrl: `${env.domain}${Path.externalPage.consentStart}?consentType=Consult`,
});
```
> fix: with consent to fetch with params

- src/components/form/PhoneNumberForm.stories.tsx
- src/components/form/PhoneNumberForm.tsx
- src/components/input/DropdownInput.stories.tsx
- src/components/input/DropdownInput.tsx
- src/components/input/InternationalPhone.tsx
- src/components/input/MobileInput.tsx
- src/components/input/TextInput.tsx
https://github.com/user-attachments/assets/7e1206bb-ce49-4f3c-8896-95ff2e44b6b8
> fix: adjust input ui according to register form

- src/components/form/PhoneNumberForm.tsx
- src/components/input/DropdownInput.tsx
- src/components/input/MobileInput.tsx
- src/components/input/RadioButton.stories.tsx
- src/components/input/RadioButton.tsx
- src/components/input/SelectGroupInput.tsx
- src/components/input/TextArea.tsx
- src/components/input/TextInput.tsx
> fix: radio button custom sx

- src/components/input/RadioButton.stories.tsx
- src/components/input/RadioButton.tsx
> fix: can custom sx style radio button

- src/components/badge/ProviderBadge.stories.tsx
- src/components/badge/ProviderBadge.tsx
- src/components/badge/index.ts
> feat: provider badge

- src/components/modal/ConfirmModal.tsx
> fix: confirm modal with custom button

- src/components/input/DOBPickerInput.tsx
https://github.com/user-attachments/assets/23bbb89f-734b-478c-bab9-f2e1c076fdf8
> fix: dob re-render text input

- src/accessCode/accessCodeForm.tsx
- src/accessCode/accessCodeProvider.tsx
- src/accessCode/index.ts
- src/utils/redirect.ts
- Add feature Access code
- Refactor checkNonProd
> feat: add access code

- publish.sh
- add exit when some command has failed during npm run publish-package
> feat: add check error when run publish-package
